/**
 * Wireframe renderer for a preview concept.
 *
 * Reads the same Preview DB record as the full preview but renders in a
 * stripped-back wireframe style: all grays, image placeholders, section
 * badges, UX annotations. The actual copy from PreviewContent is shown
 * (not Lorem Ipsum). Used for early prospect conversations.
 */
import type { PreviewContent } from "@/modules/generator/preview-types";
import type { PreviewWithLead } from "@/modules/generator/preview-store";

interface WireframePageProps {
  preview: PreviewWithLead;
}

export function WireframePage({ preview }: WireframePageProps) {
  const content = preview.contentJson as unknown as PreviewContent;
  const audit = preview.lead.audits[0];

  return (
    <div
      className="min-h-screen bg-[#F5F5F5] font-sans text-[#424242]"
      style={{ fontFamily: "system-ui, -apple-system, sans-serif" }}
    >
      {/* Wireframe banner */}
      <div className="sticky top-0 z-50 border-b border-[#BDBDBD] bg-[#424242] text-white">
        <div className="mx-auto flex max-w-6xl flex-col gap-2 px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-3">
            <SectionBadge label="WIREFRAME" />
            <p className="text-sm">
              Proposed structure for <strong>{content.meta.businessName}</strong> — generated by WLABS
            </p>
          </div>
          {audit && (
            <div className="flex items-center gap-2 text-xs text-[#BDBDBD]">
              <span>Current site score:</span>
              <span className="rounded bg-[#616161] px-2 py-0.5 font-bold text-white">{audit.overallScore}/100</span>
              <span>→ This redesign targets 85+</span>
            </div>
          )}
        </div>
      </div>

      {/* Mock nav */}
      <header className="border-b-2 border-dashed border-[#BDBDBD] bg-white">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4">
          <div className="flex items-center gap-3">
            <PlaceholderBox width={120} height={36} label="Logo" />
            <SectionBadge label="HEADER" small />
          </div>
          <nav className="hidden items-center gap-6 md:flex">
            {["Home", "Services", "About", "Contact"].map((label) => (
              <div key={label} className="h-4 rounded bg-[#E0E0E0]" style={{ width: label.length * 8 }} />
            ))}
          </nav>
          <div className="flex items-center gap-2">
            <WireframeCta label={content.hero.primaryCta.label} primary />
            <UXAnnotation label="↑ Primary CTA" />
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative border-b-2 border-dashed border-[#BDBDBD] bg-[#E0E0E0]">
        <SectionLabel label="HERO SECTION" />
        <UXAnnotation label="Above fold ✓" position="top-right" />
        <div className="mx-auto max-w-6xl px-4 py-20">
          <div className="max-w-2xl space-y-4">
            <WireframeTag label={content.hero.eyebrow} />
            <h1 className="text-4xl font-bold leading-tight text-[#212121] sm:text-5xl">{content.hero.headline}</h1>
            <p className="text-lg text-[#616161]">{content.hero.subheadline}</p>
            <div className="flex flex-wrap gap-3 pt-2">
              <WireframeCta label={content.hero.primaryCta.label} primary />
              <WireframeCta label={content.hero.secondaryCta.label} />
              <UXAnnotation label="Clear CTA above fold ✓" />
            </div>
            <div className="flex items-center gap-2 text-sm text-[#616161]">
              <span className="text-[#9E9E9E]">✓</span>
              {content.hero.trustCue}
              <UXAnnotation label="Trust signal ✓" />
            </div>
          </div>
        </div>
        <div className="absolute inset-y-0 right-8 hidden items-center md:flex">
          <PlaceholderBox width={300} height={280} label="📷 Hero image / background photo" />
        </div>
      </section>

      {/* Before / After audit */}
      {audit && (
        <section className="border-b-2 border-dashed border-[#BDBDBD] bg-white">
          <SectionLabel label="AUDIT CALLOUT" />
          <div className="mx-auto grid max-w-6xl gap-6 px-4 py-10 md:grid-cols-3">
            <WireframeCard>
              <p className="text-xs font-medium uppercase tracking-wide text-[#9E9E9E]">Current website score</p>
              <p className="mt-1 text-4xl font-bold text-[#424242]">
                {audit.overallScore}
                <span className="text-lg text-[#9E9E9E]">/100</span>
              </p>
              <ul className="mt-3 space-y-1 text-sm text-[#616161]">
                {((audit.topIssuesJson as string[] | null) ?? []).slice(0, 3).map((issue) => (
                  <li key={issue} className="flex gap-2">
                    <span className="text-red-400">•</span>
                    {issue}
                  </li>
                ))}
              </ul>
            </WireframeCard>
            <div className="flex items-center justify-center text-[#9E9E9E]">→ This redesign</div>
            <WireframeCard highlighted>
              <p className="text-xs font-medium uppercase tracking-wide text-[#9E9E9E]">Redesigned site</p>
              <p className="mt-1 text-sm text-[#424242]">
                Clean, mobile-first homepage with clear CTAs, stronger trust signals, and faster paths to contact — built to convert.
              </p>
            </WireframeCard>
          </div>
        </section>
      )}

      {/* Problem */}
      <WireframeSection label="PROBLEM SECTION" heading={content.problem.heading}>
        <div className="grid gap-4 sm:grid-cols-3">
          {content.problem.points.map((point) => (
            <WireframeCard key={point}>
              <p className="text-sm text-[#616161]">{point}</p>
            </WireframeCard>
          ))}
        </div>
      </WireframeSection>

      {/* Services */}
      <WireframeSection label="SERVICES SECTION" heading={content.services.heading} tinted>
        <p className="mb-6 text-center text-[#616161]">{content.services.intro}</p>
        <div className="grid gap-6 sm:grid-cols-3">
          {content.services.items.map((item, i) => (
            <WireframeCard key={item.title}>
              <PlaceholderBox width={40} height={40} label={String(i + 1)} />
              <h3 className="mt-3 font-semibold text-[#212121]">{item.title}</h3>
              <p className="mt-1.5 text-sm text-[#616161]">{item.description}</p>
            </WireframeCard>
          ))}
        </div>
      </WireframeSection>

      {/* Why us */}
      <WireframeSection label="WHY US SECTION" heading={content.whyUs.heading}>
        <div className="grid gap-6 sm:grid-cols-3">
          {content.whyUs.reasons.map((reason) => (
            <div key={reason.title}>
              <h3 className="font-semibold text-[#212121]">{reason.title}</h3>
              <p className="mt-1.5 text-sm text-[#616161]">{reason.description}</p>
            </div>
          ))}
        </div>
      </WireframeSection>

      {/* Trust */}
      <WireframeSection label="TRUST SECTION" heading={content.trust.heading} tinted>
        <div className="flex flex-wrap justify-center gap-3">
          {content.trust.items.map((item) => (
            <span key={item} className="rounded-full border border-[#BDBDBD] bg-white px-4 py-2 text-sm text-[#616161]">
              {item}
            </span>
          ))}
        </div>
        <div className="mt-4 flex justify-center">
          <UXAnnotation label="Trust signal section ✓" />
        </div>
      </WireframeSection>

      {/* Contact */}
      <WireframeSection label="CONTACT SECTION" heading={content.local.heading}>
        <div className="grid gap-8 md:grid-cols-2">
          <div className="space-y-4">
            {content.local.address && <p className="flex items-center gap-2 text-sm text-[#616161]">📍 {content.local.address}</p>}
            {content.local.phone && (
              <p className="flex items-center gap-2 text-sm text-[#616161]">
                📞 {content.local.phone}
                <UXAnnotation label="Click-to-call ✓" />
              </p>
            )}
            {content.local.email && <p className="flex items-center gap-2 text-sm text-[#616161]">✉️ {content.local.email}</p>}
            {content.local.serviceArea && <p className="text-sm text-[#9E9E9E]">Serving {content.local.serviceArea}</p>}
            <PlaceholderBox width="100%" height={160} label="📍 Map embed" />
          </div>
          <WireframeCard>
            <h3 className="font-semibold text-[#212121]">{content.contact.heading}</h3>
            <p className="mt-1 text-sm text-[#9E9E9E]">{content.contact.subheading}</p>
            <div className="mt-4 space-y-3">
              {content.contact.fields.map((field) => (
                <div key={field}>
                  <label className="mb-1 block text-xs font-medium text-[#9E9E9E]">{field}</label>
                  {field === "Message" ? (
                    <div className="h-20 rounded-lg border-2 border-dashed border-[#BDBDBD] bg-[#F5F5F5]" />
                  ) : (
                    <div className="h-10 rounded-lg border-2 border-dashed border-[#BDBDBD] bg-[#F5F5F5]" />
                  )}
                </div>
              ))}
              <WireframeCta label={content.contact.heading} primary fullWidth />
            </div>
          </WireframeCard>
        </div>
      </WireframeSection>

      {/* Final CTA */}
      <section className="border-b-2 border-dashed border-[#BDBDBD] bg-[#E0E0E0]">
        <SectionLabel label="FINAL CTA SECTION" />
        <div className="mx-auto max-w-4xl px-4 py-16 text-center">
          <h2 className="text-3xl font-bold text-[#212121]">{content.finalCta.heading}</h2>
          <p className="mx-auto mt-3 max-w-xl text-[#616161]">{content.finalCta.subheading}</p>
          <div className="mt-6 flex flex-wrap justify-center gap-3">
            <WireframeCta label={content.finalCta.cta.label} primary />
            <WireframeCta label="Book a 15-minute call" />
            <UXAnnotation label="Conversion CTA ✓" />
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t-2 border-dashed border-[#BDBDBD] bg-white">
        <SectionLabel label="FOOTER" />
        <div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-8 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="font-bold text-[#212121]">{content.meta.businessName}</p>
            <p className="text-sm text-[#9E9E9E]">{content.meta.tagline}</p>
          </div>
          <p className="text-xs text-[#9E9E9E]">Wireframe concept by WLABS — Website Laboratory</p>
        </div>
      </footer>
    </div>
  );
}

// ---- Primitives ----

function SectionLabel({ label }: { label: string }) {
  return (
    <div className="absolute left-4 top-2 z-10">
      <span className="rounded bg-[#424242] px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-white">[{label}]</span>
    </div>
  );
}

function SectionBadge({ label, small }: { label: string; small?: boolean }) {
  return (
    <span className={`rounded bg-[#9E9E9E] px-2 py-0.5 font-bold uppercase tracking-wide text-white ${small ? "text-[9px]" : "text-xs"}`}>
      {label}
    </span>
  );
}

function UXAnnotation({ label, position = "inline" }: { label: string; position?: "inline" | "top-right" }) {
  const base = "rounded-full border border-dashed border-[#9E9E9E] bg-white/80 px-2 py-0.5 text-[10px] font-medium text-[#9E9E9E]";
  if (position === "top-right") {
    return <span className={`absolute right-4 top-2 z-10 ${base}`}>{label}</span>;
  }
  return <span className={base}>{label}</span>;
}

function WireframeTag({ label }: { label: string }) {
  return (
    <div className="inline-block rounded border border-[#BDBDBD] bg-white px-3 py-1 text-xs font-medium uppercase tracking-wide text-[#9E9E9E]">
      {label}
    </div>
  );
}

function WireframeCta({ label, primary, fullWidth }: { label: string; primary?: boolean; fullWidth?: boolean }) {
  return (
    <div
      className={`inline-flex items-center justify-center rounded-full px-6 py-3 text-sm font-semibold ${fullWidth ? "w-full" : ""} ${
        primary
          ? "border-2 border-[#424242] bg-[#424242] text-white"
          : "border-2 border-[#9E9E9E] bg-white text-[#616161]"
      }`}
    >
      {label}
    </div>
  );
}

function PlaceholderBox({
  width,
  height,
  label,
}: {
  width: number | string;
  height: number | string;
  label: string;
}) {
  return (
    <div
      className="flex flex-shrink-0 items-center justify-center rounded-lg border-2 border-dashed border-[#BDBDBD] bg-[#EEEEEE] text-center text-xs text-[#9E9E9E]"
      style={{ width: typeof width === "number" ? `${width}px` : width, height: typeof height === "number" ? `${height}px` : height }}
    >
      {label}
    </div>
  );
}

function WireframeCard({ children, highlighted }: { children: React.ReactNode; highlighted?: boolean }) {
  return (
    <div
      className={`rounded-2xl border-2 p-5 ${
        highlighted ? "border-[#424242] bg-white" : "border-[#BDBDBD] bg-white"
      }`}
    >
      {children}
    </div>
  );
}

function WireframeSection({
  label,
  heading,
  tinted,
  children,
}: {
  label: string;
  heading: string;
  tinted?: boolean;
  children: React.ReactNode;
}) {
  return (
    <section className={`relative border-b-2 border-dashed border-[#BDBDBD] ${tinted ? "bg-[#FAFAFA]" : "bg-white"}`}>
      <SectionLabel label={label} />
      <div className="mx-auto max-w-6xl px-4 py-14 pt-10">
        <h2 className="text-center text-2xl font-bold text-[#212121] sm:text-3xl">{heading}</h2>
        <div className="mt-8">{children}</div>
      </div>
    </section>
  );
}
